config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "splash#index"

  resources :groups, only: [:index, :show, :create, :new] do
    resources :expenses, only: [:new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Group, author: user
    can :manage, Expense, author: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/classify.rb
class Classify < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/expense.rb
class Expense < ApplicationRecord
  has_many :classifies, dependent: :destroy
  has_many :groups, through: :classifies
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :classifies, dependent: :destroy
  has_many :expenses, through: :classifies
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :groups
  has_many :expenses

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  def redirect_to_splash
    redirect_to root_path unless user_signed_in?
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password)
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :redirect_to_splash
  load_and_authorize_resource
  def new
    @group = Group.find(params[:group_id])
    @expense = Expense.new
    @groups = Group.where(author_id: current_user.id)
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.author = current_user
    @group = Group.find(params[:group_id])
    if params[:group_ids]
      params[:group_ids].each do |group_id|
        group = Group.find(group_id)
        group.expenses << @expense
      end
      redirect_to @group
    else
      redirect_to new_group_payment_path(@group), flash: { alert: 'You must select at least one category.' }
      nil
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :redirect_to_splash
  load_and_authorize_resource
  def index
    @groups = Group.includes([:classifies]).where(author: current_user)
  end

  def show
    @group = Group.find(params[:id])
    @expenses = @group.expenses.order(created_at: :desc)
  end

  def create
    @group = Group.new(group_params)
    @group.author = current_user
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    redirect_to groups_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/expenses/new.html.erb
<nav>
  <div class="nav-form">
    <p class="back-white"><strong><%= link_to "< Back", groups_path %></strong></p>
    <div class="new-group-nav">
      <h1>NEW EXPENSE</h1>
      <% if user_signed_in? %>
        <ul>
          <li><%= link_to "Home", groups_path %></li>
          <li>    
            <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>
<div class="logo-container form-image">
<%= image_tag("logo.png") %>
</div>

<div class="form-container"> 
  <%= form_with(model: @expense, url: group_expenses_path(@group)) do |form| %>
    <% if @expense.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this payment from being saved:</h2>
        <ul>
          <% @expense.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
  <div class="field width-100">
    <%= form.label :name, hidden: true %>
    <%= form.text_field :name, placeholder: 'Name', required: true %>
  </div>
  
  <div class="field width-100">
    <%= form.label :amoutn, hidden: true %>
    <%= form.number_field :amount, placeholder: 'Amount', required: true %>
  </div>
  
  <div class="selections">
    <%@groups.each do |group|%>
      <div class="selection">
        <%= group.name %>
        <%= check_box_tag "group_ids[]", group.id, group.id == @group.id  %>
      </div>
    <%end%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <% end %>
</div>

app/views/groups/index.html.erb
<%= render "shared/nav" %>
<div class="mobile-container">
<div class="fill">
<% @groups.includes([:expenses]).each do |group| %>
  <div class="group-container">
    <% @total = 0 %>
    <div class="group-icon">
      <img src="<%= group.icon %>">
    </div>
    <div class="group-name">
      <h3><%= link_to group.name, group_path(group) %></h3>
    </div>
    <div class="group-total">
      <% group.expenses.each do |expense| %>
        <% @total += expense.amount %>
      <% end %>
    <p> $<%= @total %> </p>
    </div>
  </div>
<% end %>
  <footer>
    <p><%= link_to "New Category", new_group_path%></p>
  </footer>
</div>
</div>

app/views/groups/new.html.erb
<%= render "shared/nav" %>
<div class="logo-container form-image">
  <img src="../../assets/logo.png">
</div>

<div class="form-container"> 
  <%= form_with model: @group do |form|%>
    <div class="field width-100">
      <%= form.label :name, hidden: true %>
      <%= form.text_field :name, placeholder: 'Group name'%>
    </div>

    <div class="field width-100">
      <%= form.label :icon, hidden: true %>
      <%= form.text_field :icon, placeholder: 'Link to icon'%>
    </div>

    <div class="actions">
    <%= form.submit%>
    </div>
  <%end%>
</div>

app/views/groups/show.html.erb
<%= render "shared/nav" %>
<div class="mobile-container">
  <p><strong><%= link_to "< Back", groups_path, class: "back" %></strong></p>
  <p>Total spending for <%= @group.name %>:
  <strong><%@sum=0%>
  <% @expenses.each do |expense| %>
    <% @sum = @sum + expense.amount %>
  <%end%>
  $<%= @sum %>
  </p></strong>
  <% @expenses.each do |expense| %>
  <div class="expense">
    <div>
    <p> <%= expense.name %> </p>
    </div>
    <strong><p> $<%= expense.amount %> </p></strong>
  </div>
  <% end %>
  <footer>
    <p><%= link_to "New Expense", new_group_expense_path(@group)%></p>
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav>
  <% if current_page?(new_user_session_path) %>
  <div class="nav-form">
    <p class="back-white"><strong><%= link_to "< Back", groups_path %></strong></p>
    <h1>LOGIN</h1>
  </div>
  <% elsif current_page?(new_user_registration_path) %>
    <div class="nav-form">
    <p class="back-white"><strong><%= link_to "< Back", groups_path %></strong></p>
    <h1>SIGN UP</h1>
  <% elsif current_page?(new_group_path) %>
    <div class="nav-form">
    <p class="back-white"><strong><%= link_to "< Back", groups_path %></strong></p>
    <div class="new-group-nav">
      <h1>NEW GROUP</h1>
      <% if user_signed_in? %>
      <ul>
        <li><%= link_to "Home", groups_path %></li>
        <li>    
          <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
        </li>
      </ul>
    <% end %>
    </div>
  <% elsif current_page?(new_user_password_path) %>
    <div class="nav-form">
      <p class="back-white"><strong><%= link_to "< Back", groups_path %></strong></p>
      <div class="new-group-nav">
        <h1>RESET PASSWORD</h1>
        <% if user_signed_in? %>
          <ul>
            <li><%= link_to "Home", groups_path %></li>
            <li>    
              <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  <% else %>
    <h1>Spendless</h1>
    <% if user_signed_in? %>
      <ul>
        <li><%= link_to "Home", groups_path %></li>
        <li>    
          <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
        </li>
      </ul>
    <% end %>
  <% end %>
</nav>

app/views/splash/index.html.erb
<%= render "shared/nav" %>
<div class="container">
  <div class="logo-container form-image">
    <img src="../../assets/logo.png">
  </div>
  <%= link_to 'Log In', new_user_session_path, class: 'splash-btn' %> 
  <%= link_to 'Sign Up', new_user_registration_path, class: 'splash-btn' %>
</>